version: "3"

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    tty: true
    user: root
    volumes:
      - ./queries:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    container_name: db_postgresql
  api:
    build: .
    volumes:
      - .:/usr/local/src/practice_api
    environment:
      PGHOST: db
      PGUSER: practice
    tty: true
    stdin_open: true
    command: java -Djava.security.egd=file:/dev/./urandom -Dspring.datasource.driver-class-name='org.postgresql.Driver' -Dspring.datasource.url='jdbc:postgresql://db_postgresql:5432/practice' -Dspring.datasource.username='practice' -Dspring.datasource.password='practice' -jar /usr/local/practice_api/app.jar
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
volumes:
  db:
    external: false
